# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracaKlasowa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('nr_lekcji', models.CharField(max_length=30)),
                ('nauczyciel', models.CharField(max_length=30)),
                ('rodzaj', models.CharField(max_length=30)),
                ('przedmiot', models.CharField(max_length=30)),
                ('opis', models.CharField(max_length=100)),
                ('data_dodania', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=150)),
                ('klasa', models.CharField(max_length=20)),
                ('num_w_dzienniku', models.CharField(max_length=10)),
                ('oceny', models.CharField(max_length=150)),
                ('srednia', models.CharField(max_length=5)),
                ('szczesliwy_numerek', models.PositiveIntegerField(null=True)),
                ('data_numerka', models.CharField(max_length=150)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sprawdzian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('nr_lekcji', models.CharField(max_length=30)),
                ('nauczyciel', models.CharField(max_length=30)),
                ('rodzaj', models.CharField(max_length=30)),
                ('przedmiot', models.CharField(max_length=30)),
                ('opis', models.CharField(max_length=100)),
                ('data_dodania', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
