# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20171101_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprawdzianZaliczony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.CharField(max_length=5)),
                ('kategoria', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=30)),
                ('nauczyciel', models.CharField(max_length=60)),
                ('przedmiot', models.CharField(max_length=60)),
                ('komentarz', models.CharField(max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
