# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_sprawdzianzaliczony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprawdzianzaliczony',
            name='kategoria',
            field=models.CharField(choices=[('sprawdzian', 'sprawdzian'), ('kartkówka', 'kartkówka'), ('odpowiedź ustana', 'odpowiedź ustana')], default='sprawdzian', max_length=50),
        ),
    ]
