# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171106_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprawdzianzaliczony',
            name='przedmiot',
            field=models.CharField(choices=[('Biologia', 'Biologia'), ('Chemia', 'Chemia'), ('Edukacja dla bezpieczeństwa', 'EDB'), ('Fizyka', 'Fizyka'), ('Historia', 'Historia'), ('Informatyka', 'Informatyka'), ('Język angielski', 'Język angielski'), ('Język niemiecki', 'Język niemiecki'), ('Język francuski', 'Język francuski'), ('Język polski', 'Język polski'), ('Matematyka', 'Matematyka'), ('Podstawy przedsiębiorczości', 'Podstawy przedsiębiorczości'), ('Religia', 'Religia'), ('Wiedza o kulturze', 'WOK'), ('Wiedza o społeczeństwie', 'WOS'), ('Wychowanie fizyczne', 'WF'), ('default', 'Brak')], default='default', max_length=60),
        ),
    ]
