# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_auto_20171106_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiadomosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nadawca', models.CharField(max_length=100)),
                ('temat', models.CharField(max_length=250)),
                ('wiadomosc', models.TextField()),
                ('data_wyslawana', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='sprawdzianzaliczony',
            name='przedmiot',
            field=models.CharField(choices=[('default', '------------------------------------'), ('Biologia', 'Biologia'), ('Chemia', 'Chemia'), ('Edukacja dla bezpieczeństwa', 'EDB'), ('Fizyka', 'Fizyka'), ('Historia', 'Historia'), ('Informatyka', 'Informatyka'), ('Język angielski', 'Język angielski'), ('Język niemiecki', 'Język niemiecki'), ('Język francuski', 'Język francuski'), ('Język polski', 'Język polski'), ('Matematyka', 'Matematyka'), ('Podstawy przedsiębiorczości', 'Podstawy przedsiębiorczości'), ('Religia', 'Religia'), ('Wiedza o kulturze', 'WOK'), ('Wiedza o społeczeństwie', 'WOS'), ('Wychowanie fizyczne', 'WF')], default='default', max_length=60),
        ),
    ]
